apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
spec:
  selector:
    matchLabels:
      app: java-spring
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
        app: java-spring
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: java-spring
        image:  us-east1-docker.pkg.dev/datadog-402618/datadog-appoena/java-spring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env: 
            - name: DD_SERVICE
              value: java-spring
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-spring
spec:
  type: LoadBalancer
  selector:
    app: java-spring
  ports:
  - name: http
    port: 8083
    targetPort: 8080
